name: Go Lint

on:
  push:
    branches:
      - master
  # We only run tests when we open PRs (and not for ex: on every commit)
  # to avoid running workflows too frequently and incurring costs
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.20"
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54.2
          args: --timeout=3m
